### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/dsPrivacy#9]
## Problem

We don't want to spend hours debugging our code anymore. Instead, we could create an awesome test suite. 🤩 

## Implementation

- [ ] Switch to the Python best practices (see internal templates)
- [ ] Build Python unit tests (with pytest) to check that the functionalities work as intended
- [ ] Switch to the R best practices (?)
- [ ] Build R unit tests to check that imports and bindings are right
- [ ] Build a CI GH action that can install, run DataShield and load data into it
- [ ] Use this GH action to test the end2end process of calling each function.
